### ISSUE TITLE
Crash on client startup

### ISSUE THREAD

**Issue by pjlasl** [CodenameRevy/AdditionalBarsBOP#1]
I updated to 2.0.0 of additional bars and added the BOP addon since I use BOP. It crashes on client startup: https://paste.ee/p/HvJaG

**Comment by mdujovic17** [comment]
It crashes because you're using Java 15. Try with Java 11 and let me know if it crashes again.

**Comment by pjlasl** [comment]
I rolled back and that seemed to work.

**Comment by mdujovic17** [comment]
Ok, also fixed in 2.0.2

**Comment by pjlasl** [comment]
Nice, I can go back to Java 15!
